

services:
  libreria-api:
    build: .
    container_name: libreria-api
    ports:
      - "8080:8080"
    environment:
      EXTERNAL_API_BOOKS_URL: "https://my-json-server.typicode.com/Gabriel-Arriola-UTN/libros/books"
    restart: always
